### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/kotatsu#109]
There seems to be an issue with sourcemaps when deploying to Heroku, which is "production" env.

For some reason when I fire up the server it can not find the sourcemaps module. Its strange because `source-map-support` is a dependency, have no idea why it is not available.

I have not added source-maps as an option either, so not sure what causes it. I though I would create an issue first in case it makes sense to you? Or I can investigate further :)

**Comment by Yomguithereal** [comment]
> I have not added source-maps as an option either, so not sure what causes it. I though I would create an issue first in case it makes sense to you? Or I can investigate further :)

If the source maps options is disabled you won't have source maps. The related lines are [here](https://github.com/Yomguithereal/kotatsu/blob/master/src/createCompiler.js#L198-L211).

**Comment by Yomguithereal** [comment]
Any news about this?

**Comment by christianalfoni** [comment]
Hm, this is really strange. Maybe its because it is dynamic? Any reason you are not just requiring it as normal?

**Comment by christianalfoni** [comment]
ah, wait, yeah, I see now... hm

**Comment by christianalfoni** [comment]
But its still weird... because kotatsu does have it as dependency so it should be available. But something might happen to the path maybe? Hm hm

**Comment by Yomguithereal** [comment]
Do you have an error stating it's not available?

**Comment by christianalfoni** [comment]
Doing a deploy now to test... lets see

**Comment by christianalfoni** [comment]
The strange thing is that it does not happen on build, it happens when the application is running:

```
2016-02-26T14:50:08.891754+00:00 app[web.1]: Error: Cannot find module '/tmp/build_80294b01d2dd820e5f68216b4555c974/christianalfoni-webpack-bin-c26a8d9/node_modules/source-map-support/source-map-support.js'
2016-02-26T14:50:08.891755+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:339:15)
2016-02-26T14:50:08.891755+00:00 app[web.1]:     at Function.Module._load (module.js:290:25)
2016-02-26T14:50:08.891756+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-02-26T14:50:08.891756+00:00 app[web.1]:     at require (internal/module.js:16:19)
2016-02-26T14:50:08.891757+00:00 app[web.1]:     at Object.<anonymous> (/app/server_build.js:1:63)
2016-02-26T14:50:08.891757+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-02-26T14:50:08.891758+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-02-26T14:50:08.891758+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-02-26T14:50:08.891758+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-02-26T14:50:08.891759+00:00 app[web.1]:     at Function.Module.runMain (module.js:447:10)
2016-02-26T14:50:08.912843+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-02-26T14:50:08.901301+00:00 app[web.1]:
```

**Comment by christianalfoni** [comment]
Maybe because you set default devtools?

**Comment by christianalfoni** [comment]
Should not do that in production no matter what?

**Comment by Yomguithereal** [comment]
But why isn't the module found anyway?

**Comment by christianalfoni** [comment]
Ah yeah! I see it!

`/tmp/build_80294b01d2dd820e5f68216b4555c974/christianalfoni-webpack-bin-c26a8d9/node_modules/source-map-support/source-map-support.js`

This is probably removed by Heroku, as it is tmp. Maybe Heroku tries to identify the packages you need by going through the code or something? Since source-map is never required it will not be included. Sounds a bit crazy... though, could be?

**Comment by Yomguithereal** [comment]
Sounds crazy indeed but it could be the case. You should disable source maps through `--no-source-maps`.

**Comment by christianalfoni** [comment]
So the devtools thingy here can not be it? It is always false in production?

**Comment by Yomguithereal** [comment]
By default it's true since we changed the default value remember?

**Comment by christianalfoni** [comment]
Yeah, thats what I meant :) I would suggest setting it to `default=false` in production :)

Because now if I do not have any sourcemaps it will still try to load the sourcemaps since the devtools are true :)

**Comment by Yomguithereal** [comment]
Any news on this @christianalfoni?

**Comment by christianalfoni** [comment]
The webpackbin project was starting to become a bit complex, also using websockets so I decided to move to plain Node stuff. Still love kotatsu though, really nice to get going, but yeah... when you get to a point of complexity it gets hard to handle all of it in kotatsu... the story of abstractions :)

**Comment by Yomguithereal** [comment]
Hello @christianalfoni. This is the goal of kotatsu anyway to let you start a project fast and to introduce the full tweaked stack only when this is really needed. So I guess it fulfilled its contract :)
